import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { z } from "zod";
import { ArrowLeftIcon, Loader2Icon, RefreshCwIcon } from "lucide-react";
import { DeleteGenerationButton, GenerationDetailsDialog } from "@/components/ai/generation-actions";
import { AiStatusBadge } from "@/components/ai/ai-status-badge";
import { PendingRefresh } from "@/components/ai/pending-refresh";
import { ScriptEditor } from "@/components/ai/script-editor";
import { PageHeader } from "@/components/app/page-header";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { briefDefaultsFrom, formatSeconds, isStalePending, readScript } from "@/lib/ai/studio";
import { canManageWork, isStaff } from "@/lib/permissions";
import { createClient } from "@/lib/supabase/server";
import { formatDate, formatRelativeTime } from "@/lib/utils";
import { getWorkspaceContext } from "@/lib/workspace";

export const metadata: Metadata = { title: "Script" };
export const maxDuration = 300;

export default async function AiGenerationPage({ params }: PageProps<"/app/ai-studio/[generationId]">) {
  const { user, active } = await getWorkspaceContext();
  if (!isStaff(active.role)) notFound();
  const { generationId } = await params;
  if (!z.uuid().safeParse(generationId).success) notFound();

  const supabase = await createClient();
  const [{ data: g, error }, projects] = await Promise.all([
    supabase
      .from("ai_generations")
      .select("*")
      .eq("id", generationId)
      .eq("workspace_id", active.id)
      .eq("kind", "script")
      .maybeSingle(),
    supabase.from("projects").select("id, name, archived_at").eq("workspace_id", active.id).order("name").limit(500),
  ]);
  if (error || projects.error) throw new Error(`Could not load the script: ${(error ?? projects.error)?.message}`);
  if (!g) notFound();

  const peopleIds = [g.created_by, g.edited_by].filter((x): x is string => Boolean(x));
  const { data: profiles } = peopleIds.length
    ? await supabase.from("profiles").select("id, full_name, email").in("id", peopleIds)
    : { data: [] as { id: string; full_name: string | null; email: string }[] };
  const nameOf = (id: string | null) => {
    if (id === user.id) return "you";
    const p = profiles?.find((x) => x.id === id);
    return p?.full_name ?? p?.email ?? "a former member";
  };

  const script = readScript(g.document) ?? readScript(g.output);
  const canEdit = g.created_by === user.id || canManageWork(active.role);
  const stale = isStalePending(g.status, g.created_at);
  const failed = g.status === "failed" || stale;
  const brief = briefDefaultsFrom(g);
  const allProjects = projects.data ?? [];
  const project = allProjects.find((p) => p.id === g.project_id);
  const title = g.title ?? script?.title ?? "Untitled script";
  const tokens = (g.input_tokens ?? 0) + (g.output_tokens ?? 0);

  return (
    <div className="grid gap-6">
      <Link
        href="/app/ai-studio"
        className="inline-flex w-fit items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
      >
        <ArrowLeftIcon className="size-4" /> AI Studio
      </Link>
      <PageHeader
        title={title}
        description={
          <span className="inline-flex flex-wrap items-center gap-2">
            <AiStatusBadge status={g.status} createdAt={g.created_at} />
            <span>
              Generated by {nameOf(g.created_by)} {formatRelativeTime(g.created_at)}
              {g.edited_at ? ` · edited by ${nameOf(g.edited_by)} ${formatRelativeTime(g.edited_at)}` : ""}
            </span>
          </span>
        }
        actions={
          <>
            {g.status === "completed" || failed ? (
              <Button asChild variant={failed ? "brand" : "outline"}>
                <Link href={`/app/ai-studio?from=${g.id}`}>
                  <RefreshCwIcon /> {failed ? "Try again" : "New version"}
                </Link>
              </Button>
            ) : null}
            {canEdit ? (
              <>
                <GenerationDetailsDialog
                  generationId={g.id}
                  title={g.title ?? ""}
                  projectId={g.project_id ?? ""}
                  projects={allProjects
                    .filter((p) => !p.archived_at || p.id === g.project_id)
                    .map((p) => ({ id: p.id, name: p.name }))}
                />
                <DeleteGenerationButton generationId={g.id} label={`“${title}”`} />
              </>
            ) : null}
          </>
        }
      />

      <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_20rem]">
        <div className="min-w-0">
          {g.status === "pending" && !stale ? (
            <Alert>
              <Loader2Icon className="animate-spin" />
              <AlertTitle>Still writing this script</AlertTitle>
              <AlertDescription>
                This page checks again every few seconds. Runs that don&apos;t finish within 15 minutes are marked as
                failed.
              </AlertDescription>
              <PendingRefresh />
            </Alert>
          ) : failed ? (
            <Alert variant="destructive">
              <AlertTitle>This script wasn&apos;t generated</AlertTitle>
              <AlertDescription>
                {stale ? "It timed out before the AI result arrived." : (g.error ?? "The AI run failed.")} Choose Try
                again to reuse the brief.
              </AlertDescription>
            </Alert>
          ) : script ? (
            <ScriptEditor generationId={g.id} script={script} canEdit={canEdit} />
          ) : (
            <Alert variant="destructive">
              <AlertTitle>The script couldn&apos;t be read</AlertTitle>
              <AlertDescription>Generate a new version from the same brief.</AlertDescription>
            </Alert>
          )}
        </div>

        <aside className="grid h-fit gap-4">
          <Card>
            <CardHeader>
              <CardTitle className="text-base">Brief</CardTitle>
            </CardHeader>
            <CardContent>
              <dl className="grid gap-3 text-sm">
                {brief.brief ? <Detail label="Brief" value={brief.brief} /> : null}
                <Detail label="Length" value={formatSeconds(Number(brief.durationSeconds))} />
                {brief.tone ? <Detail label="Tone" value={brief.tone} /> : null}
                {brief.platform ? <Detail label="Platform" value={brief.platform} /> : null}
                {brief.audience ? <Detail label="Audience" value={brief.audience} /> : null}
                {brief.callToAction ? <Detail label="Call to action" value={brief.callToAction} /> : null}
                <div className="grid gap-0.5">
                  <dt className="text-muted-foreground">Project</dt>
                  <dd>
                    {project ? (
                      <Link href={`/app/projects/${project.id}`} className="font-medium hover:underline">
                        {project.name}
                      </Link>
                    ) : (
                      "None"
                    )}
                  </dd>
                </div>
              </dl>
            </CardContent>
          </Card>
          {g.model || tokens ? (
            <Card>
              <CardHeader>
                <CardTitle className="text-base">Run</CardTitle>
              </CardHeader>
              <CardContent>
                <dl className="grid gap-3 text-sm">
                  {g.model ? <Detail label="Model" value={g.model} /> : null}
                  {tokens ? (
                    <Detail
                      label="Tokens"
                      value={`${(g.input_tokens ?? 0).toLocaleString("en-US")} in · ${(g.output_tokens ?? 0).toLocaleString("en-US")} out`}
                    />
                  ) : null}
                  {g.completed_at ? <Detail label="Finished" value={formatDate(g.completed_at)} /> : null}
                </dl>
              </CardContent>
            </Card>
          ) : null}
        </aside>
      </div>
    </div>
  );
}

function Detail({ label, value }: { label: string; value: string }) {
  return (
    <div className="grid gap-0.5">
      <dt className="text-muted-foreground">{label}</dt>
      <dd className="whitespace-pre-line">{value}</dd>
    </div>
  );
}
